In [1]:
import os
import json

In [2]:
main_folder = 'RIS_fingerprint_isomorphism_random_modified_graph'
folder_sudies_path = 'RIS_fingerprint_images_folders_studies'

folders = os.listdir(main_folder)
folders.sort()
#print(folders)

number_edge_matches = {}
first = True

same_graph = {}
same_finger = {}
same_person = {}
same_family = {}
strangers = {}

name_family_1 = '00'

for folder in folders:
    #if first:

        path_current_folder = main_folder + "/" + folder
        #print(folder)
        files = os.listdir(main_folder + '/' + folder)

        if 'data_matches.json' in files:
            files.remove('data_matches.json')

        name1 = folder[0:11]
        name2 = folder[12:]

        name_fam_tem = name1[0:2]
        if name_fam_tem != name_family_1:
            name_family_1 = name_fam_tem
            print(name_family_1)

        for file in files:
        
            file_json = open(path_current_folder + '/' + file,'r')
            data_subgraphs = json.load(file_json)

            if 'subgraphs' in data_subgraphs:

                data_subg1 = data_subgraphs['subgraphs']['subgraph_g1']
                nodes_sub_g1 = data_subg1['nodes']
                score = len(nodes_sub_g1)

                if name1 != name2:
                    if name1[0:2] == name2[0:2]:
                        if name1[3:5] == name2[3:5]:
                            if name1[6:8] == name2[6:8]:
                                if score not in same_finger:
                                    same_finger[score] = 1
                                else:
                                    same_finger[score] = same_finger[score] + 1
                            else:
                                if score not in same_person:
                                    same_person[score] = 1
                                else:
                                    same_person[score] = same_person[score] + 1
                        else:
                            if (name1[3:5] == 'B0' and name2[3:5] == 'C0') or (name1[3:5] == 'C0' and name2[3:5] == 'B0'):
                                if score not in strangers:
                                    strangers[score] = 1
                                else:
                                    strangers[score] = strangers[score] + 1
                            else:
                                if score not in same_family:
                                    same_family[score] = 1
                                else:
                                    same_family[score] = same_family[score] + 1
                    else:
                        if score not in strangers:
                            strangers[score] = 1
                        else:
                            strangers[score] = strangers[score] + 1
                else:
                    if score not in same_graph:
                        same_graph[score] = 1
                    else:
                        same_graph[score] = same_graph[score] + 1


    #first = False

print(len(same_graph))
print(len(same_finger))
print(len(same_person))
print(len(same_family))
print(len(strangers))            


data_file = {'same_graph': same_graph,
             'same_finger': same_finger,
             'same_person': same_person,
             'same_family': same_family,
             'strangers': strangers}

with open('num_cluster_nodes.json', 'w') as file_json_out:
            json.dump(data_file,file_json_out)

01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
0
19
28
25
24


In [3]:
import numpy as np
#print(same_person.keys())
same_person_key_array = np.array(list(same_person.keys()))
print(same_person_key_array)
#print(same_person.values())
same_person_val_array = np.array(list(same_person.values()))
print(same_person_val_array)
sorted_values_index_person = np.argsort(same_person_val_array)
same_person_key_array[sorted_values_index_person]

[ 2  3  4  5  6  8 12  7 14  9 10 11 13 16 15 17 21 24 18 20 79 31 34 28
 19 30 27 26]
[852403 133758  38087  14587   6520   1863    231   3379     72    992
    554    377    181     25     54     48     18      1     15     16
      4      1      1      5     12      3      3      2]


array([34, 31, 24, 26, 30, 27, 79, 28, 19, 18, 20, 21, 16, 17, 15, 14, 13,
       12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [4]:
#print(same_person.keys())
same_family_key_array = np.array(list(same_family.keys()))
print(same_family_key_array)
#print(same_person.values())
same_family_val_array = np.array(list(same_family.values()))
print(same_family_val_array)
sorted_values_index_family = np.argsort(same_family_val_array)
print(same_family_key_array[sorted_values_index_family])

[ 2  5  4  3  8  6 10 12  7  9 11 19 15 16 22 13 14 17 25 18 21 24 20 23
 28]
[1159537   18999   50618  179546    2373    8296     700     255    4214
    1295     450      28     109      41      10     163     129      55
       5      26       3      10       2       1       8]
[23 20 21 25 28 24 22 18 19 16 17 15 14 13 12 11 10  9  8  7  6  5  4  3
  2]


In [5]:
#print(same_person.keys())
same_strangers_key_array = np.array(list(strangers.keys()))
print(same_strangers_key_array)
#print(same_person.values())
same_strangers_val_array = np.array(list(strangers.values()))
print(same_strangers_val_array)
sorted_values_index_strangers = np.argsort(same_strangers_val_array)
same_strangers_key_array[sorted_values_index_strangers]

[ 2  3  6  5  4  7  8 10  9 17 13 12 14 11 15 16 20 25 22 18 19 23 21 24]
[1635613  252640   12066   26635   71003    5910    2994     971    1768
      38     226     367     159     597     120      78      13       1
      11      23      26       4      14       5]


array([25, 23, 24, 22, 20, 21, 18, 19, 17, 16, 15, 14, 13, 12, 11, 10,  9,
        8,  7,  6,  5,  4,  3,  2])

In [6]:
#print(same_person.keys())
same_finger_key_array = np.array(list(same_finger.keys()))
print(same_finger_key_array)
#print(same_person.values())
same_finger_val_array = np.array(list(same_finger.values()))
print(same_finger_val_array)
sorted_values_index_finger = np.argsort(same_finger_val_array)
same_finger_key_array[sorted_values_index_finger]

[ 2  3  4  6  5 10  7  8  9 11 15 12 13 21 20 14 18 62 16]
[41254  7010  2083   418   876    44   239   127    62    35    10    24
     4     4     5     5     1     6     1]


array([16, 18, 21, 13, 14, 20, 62, 15, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2])

In [7]:
print(max(same_finger_key_array))
print(same_finger[max(same_finger_key_array)])
print(max(same_person_key_array))
print(same_person[max(same_person_key_array)])
print(max(same_family_key_array))
print(same_family[max(same_family_key_array)])
print(max(same_strangers_key_array))
print(strangers[max(same_strangers_key_array)])

62
6
79
4
28
8
25
1


In [8]:
same_finger_esploded = []

for k,v in same_finger.items():
    to_add = [k for e in range(0,v)]
    same_finger_esploded.extend(to_add)

print(sum(same_finger_val_array))
len(same_finger_esploded)

52208


52208

In [9]:
same_person_esploded = []

for k,v in same_person.items():
    to_add = [k for e in range(0,v)]
    same_person_esploded.extend(to_add)

print(sum(same_person_val_array))
len(same_person_esploded)

1053212


1053212

In [10]:
same_family_esploded = []

for k,v in same_family.items():
    to_add = [k for e in range(0,v)]
    same_family_esploded.extend(to_add)

print(sum(same_family_val_array))
len(same_family_esploded)

1426873


1426873

In [11]:
strangers_esploded = []

for k,v in strangers.items():
    to_add = [k for e in range(0,v)]
    strangers_esploded.extend(to_add)

print(sum(same_strangers_val_array))
len(strangers_esploded)

2011282


2011282

In [12]:
data_file = {'same_graph': same_graph,
             'same_finger': same_finger,
             'same_person': same_person,
             'same_family': same_family,
             'strangers': strangers}

with open('num_cluster_nodes.json', 'w') as file_json_out:
            json.dump(data_file,file_json_out)